// https://hyper.is#cfg

module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 12.5,
    fontFamily: 'SF Mono',
    fontWeight: 'normal',
    fontWeightBold: 'bold',
    lineHeight: 1.075,
    letterSpacing: 0,
    cursorColor: '#f2ff00',
    cursorAccentColor: '#000000',
    cursorShape: 'block',
    cursorBlink: true,
    foregroundColor: '#ffffff',
    backgroundColor: '#000000a6',
    selectionColor: '#f2ff0040',
    borderColor: '#00000000',
    css: '',
    padding: '12px 16px',
    colors: {
      red: '#ff1235',
      green: '#2cf246',
      yellow: '#f2ff00',
      blue: '#00a6ff',
      magenta: '#ff4faa',
      cyan: '#30e6e6',
      white: '#ffffff',
      lightBlack: '#000000',
      lightRed: '#ff1235',
      lightGreen: '#2cf246',
      lightYellow: '#f2ff00',
      lightBlue: '#00a6ff',
      lightMagenta: '#ff4faa',
      lightCyan: '#30e6e6',
      lightWhite: '#ffffff',
    },
    shell: '/bin/zsh',
    shellArgs: ['--login'],
    env: {},
    windowSize: [540, 380],
    scrollback: 1000,
    copyOnSelect: false,
    quickEdit: false,
    defaultSSHApp: false,
    macOptionSelectionMode: 'vertical',
    webGLRenderer: true,
    webLinksActivationKey: '',
    disableLigatures: true,
    disableAutoUpdates: false,
    screenReaderMode: false,
  },
  plugins: [],
  localPlugins: [],
  keymaps: {},
};
